### ISSUE TITLE
请问可以不加载断点吗？

### ISSUE THREAD

**Issue by FallingSlowly** [Doragd/Chinese-Chatbot-PyTorch-Implementation#2]
#加载断点,从上次结束地方开始
    if opt.model_ckpt:
        checkpoint = torch.load(opt.model_ckpt)
        encoder.load_state_dict(checkpoint['en'])
        decoder.load_state_dict(checkpoint['de'])

您好，我用自己的语料在这一步总是报错 
size mismatch for embedding.weight: copying a param with shape torch.Size([6124, 256]) from checkpoint, the shape in current model is torch.Size([54, 256]).
请问可以不加载断点吗？谢谢~

**Comment by Doragd** [comment]
config文件那里面的model_ckpt = None就好了
或者你命令行运行的时候: python3 train.py --model_ckpt=None
如果要用自己的语料库的话，先要运行datapreprocess.py生成corpus.pth

**Comment by FallingSlowly** [comment]
@Doragd 多谢多谢，还想请问一下评价指标可以自己写MAP、MRR这种吗？

**Comment by Doragd** [comment]
@FallingSlowly 很抱歉，我所理解的mAP指标用在目标检测上，我不是很能理解为什么用mAP，对于对话生成任务来说，我所了解的是用PPL困惑度指标。当然，你可以实现该指标，我最近没有太多时间qwq

**Comment by FallingSlowly** [comment]
@Doragd 好的 谢谢
