### ISSUE TITLE
关于训练时出现的NaN问题

### ISSUE THREAD

**Issue by super233** [Doragd/Chinese-Chatbot-PyTorch-Implementation#5]
大佬您好，我再使用您的代码训练`qingyun`数据时，出现**Encoder的输出全部为nan**，进而导致loss为nan，请问您当时遇到过这种情况吗？

**Comment by zhifliao** [comment]
遇到相同的问题，发现只要训练到2000次以上就会出现，请问大佬当时是如何解决的？

**Comment by super233** [comment]
我当时把 **`decoder_learning_ratio`设为`1.0`** 后，训练起来就还不错

![image-20191223091056754](https://user-images.githubusercontent.com/35358984/79947938-7aa00880-84a5-11ea-81a3-460365575c9b.png)

![image-20191223091220405](https://user-images.githubusercontent.com/35358984/79947972-8ab7e800-84a5-11ea-9f2f-14044e7bd654.png)

**Comment by zhifliao** [comment]
收到，非常感谢，我修改运行试试。









--------------------------------------------------------------------------------





------------------ 原始邮件 ------------------




 
 发件人: Super233  <notifications@github.com>
 

 
 发送时间: 2020-04-22 14:28:51
 

 
 收件人:Doragd/Chinese-Chatbot-PyTorch-Implementation <chinese-chatbot-pytorch-implementation@noreply.github.com> 

 
 抄送:廖志芳 <13902220306@139.com>,Comment <comment@noreply.github.com> 

 
 主题: Re: [Doragd/Chinese-Chatbot-PyTorch-Implementation] 关于训练时出现的NaN问题 (#5)
 





 我当时把 decoder_learning_ratio设为1.0 后，训练起来就还不错
