### ISSUE TITLE
您好，必须是torch为1.0.1么？我安装，它提示没这个版本

### ISSUE THREAD

**Issue by jobsfan** [Doragd/Chinese-Chatbot-PyTorch-Implementation#6]
![1111](https://user-images.githubusercontent.com/3395025/82782004-de936380-9e8d-11ea-82be-be64dd9b2a44.png)

**Comment by Doragd** [comment]
Thanks for your interest. You can use the latest version of PyTorch. No plans to update this repo in the near future.
