### ISSUE TITLE
这个结果简直惨不忍睹啊

### ISSUE THREAD

**Issue by jobsfan** [Doragd/Chinese-Chatbot-PyTorch-Implementation#7]
![11111](https://user-images.githubusercontent.com/3395025/84230226-13eeb100-ab1e-11ea-911a-a13b77c6b754.png)

这个要从哪几个方面调试？

**Comment by jobsfan** [comment]
换了青云的预料，结果好一些，但是它生成的回答结尾总有一些莫名其妙的重复。

> 不明白你说啥麻烦您老说明白点
Bot: 这 都 你 也 太笨 了 点 吧 吧 哦 呀 呀 呀 呀
> 你在干嘛
Bot: 除了 聊天 还是 聊天 聊天 呀 呀 哟 滴 滴 个 滴 啊
> 你是傻逼吗
Bot: 你 才 傻 了 傻 逼 ， 傻 逼 就 傻 逼 啦 傻 逼 ， 傻 逼
> 卧槽
Bot: 网友 ！ 你 不 觉得 在 女生 面前 要 斯文 点 吗 哦 嘛 了
> 哈哈哈哈
Bot:  呀 呀 哟 滴 个 滴 啊 个
> 我喜欢你
Bot: 你 到底 喜欢 我 什么 ， 我 改 还 不成 吗 ？ 下 。 喜欢 。
> 我想你
Bot: 我 也 想 你 啦 呀 哦
> 我们一起私奔吧
Bot: 你 吵 不过 我 的 ！ 第二 ！ 请 ！ 吃饭 ！ 吃饭 ！
> 拜拜
Bot: 嗯 啊 ， 再见 ， 我会 想 你 的 。 让 我
> 你喜欢我吗
Bot: 当然 是 啊 啊 。 喜欢 。 喜欢 。 喜欢 。 喜欢
> 你吃那么多干啥
Error: Encountered unknown word.
> 你吃太多了
Bot: 叼 ， 独吃 难肥 啊 ！ 一齐 吃 啦 笨 ！ 笨 ！ 愛 ！ 吃饭 ！
> 你长太胖了
Bot: 我 也 是 逼 哦 ！ 有事 跟 你 做 朋友 呀 呀
> 你胆儿肥了
Error: Encountered unknown word.
> 你太猛了
Error: Encountered unknown word.
> 你放屁
Bot: 你 才 是 的 ！ 千方百计 呀 ， 跟 我 说话 的 ， 又 怪 我
> 瞎说啥呀
Bot: 虽然 是 瞎说 ， 不过 ， 也 蛮 有 道理 的 嘛 出来
> 你不是人
Bot: 想 买 就 能 卖 呀 呀 哟 滴 哟
> 聊天了
Bot: 额 聊得 开心 不 ？ 哟 啊 ！ 滴个 啊 ？ 。
> 你说的啥
Bot: 我 有 说 过 吗 ？ 呀 ， 我 忘 了 名 了 名 呗
> 你是真的傻
Bot: 你 是 傻 b 中 的 战斗机 ， 贱人 中 的 vip 的 。 假 的 。
> 交个朋友
Error: Encountered unknown word.
> 累不累
Bot: 累得 快 说不出 话 来 了 呀 哟 滴 哟
>

**Comment by albertyou2** [comment]
没有推导，没有上下文，没有记忆力，感觉现在深度学习还是比较浅，估计要通用人工智能来解决这个问题

**Comment by bournes** [comment]
可以去看GPT2的

**Comment by Doragd** [comment]
This repo is to build a toy example of Chinese Chabot. You can make a stronger one by powerful generative pre-trained models, such as UniLM, MASS, or GPT2. No plans to update this repo in the near future.

**Comment by WenjiaRan** [comment]
> 可以去看GPT2的

好感慨啊, 现在gpt4都已经被广泛应用了, 才三年
